---
name: Renovate PR Checks
on:
  pull_request:
    branches:
      - main
concurrency:
  group: renovate-pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bazel-tests:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
    container:
      image: gcr.io/bazel-public/bazel:7.1.2
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup git config
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Fetch bazel cache
        uses: actions/cache@v4
        with:
          path: /tmp/cache
          key: bazel-cache
          restore-keys: |
            bazel-cache
      - name: Bazel test
        run: bazel --output_user_root=/tmp/cache test --test_output=errors //...
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
