---
name: Renovate Auto-merge
on:
  workflow_run:
    workflows:
      - Renovate PR Checks
    types:
      - completed

jobs:
  enable-automerge:
    if: >-
      github.event.workflow_run.conclusion == 'success' &&
      startsWith(github.event.workflow_run.head_branch, 'renovate/') &&
      github.event.workflow_run.pull_requests[0].number != null
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.workflow_run.pull_requests[0].number }}
          merge-method: squash
